In [1]:
import datetime
import socket

# Get local time
local_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Get computer ID or hostname
computer_id = socket.gethostname()

# Print output with local time and computer ID
print('Assignment 1 & 2: Solutions by Nirali') # Please change your name here
print('Local Time:', local_time)
print('Computer ID:', computer_id)

Assignment 1 & 2: Solutions by Nirali
Local Time: 2023-07-04 09:37:26
Computer ID: Niralis-MacBook-Air.local


In [5]:
#Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array.


import numpy as np
def create2DArray():
    arr_1 = np.random.randint(1,10, size=(4,5))
    return arr_1

def maxInteger(arr):
    return np.max(arr)

arr_1 = create2DArray()
print("Array", arr_1)
print("Max Integer is ", maxInteger(arr_1))

Array [[6 6 5 7 7]
 [4 5 7 7 4]
 [8 1 6 5 6]
 [5 3 9 8 4]]
Max Integer is  9


In [10]:
#Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

import numpy as np
def createFloatArray(size):
    return np.random.random(size)

def reshapeArray(arr, row, col):
    return arr.reshape(row, col)

def calMean(arr):
    return np.mean(arr, axis=1)

arr_1 = createFloatArray(20)
print("1D array\n ",arr_1)
reshaped_arr = reshapeArray(arr_1, 4, 5)
print("2D array of 4x5\n ", reshaped_arr)
print("Mean\n", calMean(reshaped_arr))
    

1D array
  [0.52455828 0.68868071 0.42542232 0.89398727 0.92845714 0.68431127
 0.53112239 0.99642482 0.33140482 0.37860134 0.92609032 0.1108722
 0.0124561  0.95960694 0.92256082 0.63310258 0.65889992 0.03488827
 0.19318981 0.70135595]
2D array of 4x5
  [[0.52455828 0.68868071 0.42542232 0.89398727 0.92845714]
 [0.68431127 0.53112239 0.99642482 0.33140482 0.37860134]
 [0.92609032 0.1108722  0.0124561  0.95960694 0.92256082]
 [0.63310258 0.65889992 0.03488827 0.19318981 0.70135595]]
Mean
 [0.69222114 0.58437293 0.58631728 0.44428731]


In [12]:
#Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.
import numpy as np
def create2DArray(row, col):
    arr_1 = np.random.randint(1,101, size=(row, col))
    return arr_1

def stdDev(arr):
    return np.std(arr, axis=0)

arr_1 = create2DArray(5, 5)
print("Array", arr_1)
print("Standard Deviation is ", stdDev(arr_1))

Array [[52 97 53 16 78]
 [39 46 37 11 99]
 [96 37 60 77  6]
 [83 26 30 44 32]
 [63 33 82 97 85]]
Standard Deviation is  [20.59708717 25.43540839 18.29316812 33.60357124 35.12833614]


In [16]:
#Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

import numpy as np

# Create a 1D array of size 15 with random floats between -10 and 10
def createArray(size):
    return np.random.uniform(-10, 10, size=size)

# Replace negative values with their absolute values
def toAbsolute(arr):
    return np.abs(arr)

arr_1 = createArray(15)
print("Original array:\n", arr_1)
print("Array with absolute\n", toAbsolute(arr_1))

Original array:
 [ 9.98922782  2.26997022  8.84472318 -5.49437151 -8.04295277  7.56124326
 -7.48502766 -3.82261845 -1.6692553  -5.97396423  1.63423407 -0.46682549
 -0.87836497  5.87929609  0.59667732]
Array with absolute
 [9.98922782 2.26997022 8.84472318 5.49437151 8.04295277 7.56124326
 7.48502766 3.82261845 1.6692553  5.97396423 1.63423407 0.46682549
 0.87836497 5.87929609 0.59667732]


In [18]:
#Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

import numpy as np

def createArray(row, col):
    return np.random.randint(1, 101, size=(row,col))

def totalSum(arr):
    return np.sum(arr)

arr_1 = createArray(3,5)
print("Original array:\n", arr_1)
print("Sum\n", totalSum(arr_1))


Original array:
 [[48 54 43 53  3]
 [59 25 24 94 72]
 [55 37 56 12 53]]
Sum
 688


In [23]:
#Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.
import numpy as np

def createArray(row, col):
    return np.random.rand(row, col)

def calColMean(arr):
    return np.mean(arr, axis=0)

def colStdDeviation(arr):
    return np.std(arr, axis=0)

# Normalize each column
def normalizeCol(arr, col_mean, column_std):
    arr_normalized = (arr - col_mean) / column_std
    return arr_normalized

print(createArray(4,6))
print("\n")
arr = createArray(4, 6)
col_mean = calColMean(arr)
col_std = colStdDeviation(arr)
print("Normalized array", normalizeCol(arr, col_mean, col_std))

[[0.48515004 0.56781908 0.1223856  0.42982557 0.85050157 0.75738485]
 [0.76975909 0.3514263  0.17189685 0.15933536 0.10366688 0.70761384]
 [0.6055687  0.94458097 0.44110845 0.14487774 0.10518492 0.64844396]
 [0.40980995 0.65483084 0.0765316  0.03960104 0.33058296 0.70236038]]


Normalized array [[ 1.64112745  0.98156102  1.19418658  0.65045145 -1.0229966  -1.4976838 ]
 [-1.02461542  0.95331077  0.76820534 -0.34860577 -0.02734916 -0.15067725]
 [-0.49104055 -1.32511741 -0.81047985 -1.45664707  1.62087285  0.39076819]
 [-0.12547148 -0.60975438 -1.15191207  1.15480138 -0.5705271   1.25759287]]


In [37]:
#Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

arr = np.random.randint(1, 101, size=(10, 10))

# Replace values greater than 50 with 1 and others with 0
arr_modified = np.where(arr > 50, 1, 0)

print("Original array:")
print(arr)
print("\nModified array:")
print(arr_modified)




Original array:
[[ 21  58  59  15   9  15  90  94  35  39]
 [ 83  84  10  56  15   9  68   1   8  82]
 [ 95  44  15  45  80  43  70  13  51  34]
 [ 53   6  24  24  71  79  28  11  84  17]
 [  2  32  78  62   8  71  78  23  81  68]
 [ 46   2  91  18  51  22  37  25  39  30]
 [ 93  45  32  19   8  55  64  40  12  85]
 [ 67  17  74  52  10  86  61  28  12  95]
 [ 20  81  82   3  15  42  14  66  74  76]
 [ 86  47 100  53  16  36  86  23  35  56]]

Modified array:
[[0 1 1 0 0 0 1 1 0 0]
 [1 1 0 1 0 0 1 0 0 1]
 [1 0 0 0 1 0 1 0 1 0]
 [1 0 0 0 1 1 0 0 1 0]
 [0 0 1 1 0 1 1 0 1 1]
 [0 0 1 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 1 0 0 1]
 [1 0 1 1 0 1 1 0 0 1]
 [0 1 1 0 0 0 0 1 1 1]
 [1 0 1 1 0 0 1 0 0 1]]


In [35]:
#Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

def createFloat1DArray(size):
    return np.random.random(size)
    
def returnCountGreaterThan(arr):
    count = np.sum(arr > 0.5)
    return count
    
arr = createFloat1DArray(50)
print("Array\n", arr)
print("Count of number greater than 0.5 is",returnCountGreaterThan(arr))


Array
 [0.63368288 0.60688953 0.48112615 0.33492279 0.99329861 0.18871643
 0.17533302 0.26850767 0.8046508  0.75544609 0.55718545 0.88483388
 0.95001918 0.96350596 0.00331251 0.6519382  0.69827976 0.18557601
 0.61389077 0.12695559 0.75643325 0.80805748 0.71837676 0.69917137
 0.57820515 0.77190472 0.0481202  0.59369595 0.98081707 0.29672768
 0.217368   0.47139638 0.52927448 0.22958303 0.41073848 0.24568824
 0.47032688 0.64212711 0.04400646 0.99571547 0.39742562 0.76307197
 0.85112835 0.85085891 0.85274639 0.37359942 0.56964105 0.26718406
 0.51567428 0.48080488]
Count of number greater than 0.5 is 29


In [39]:
#Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

def createArray(row, col):
    return np.random.uniform(-1, 1, size=(row, col))

# Calculate the absolute difference between the maximum and minimum values in each row

def absDifference(arr):
    return np.abs(np.max(arr, axis=1) - np.min(arr, axis=1))

arr = createArray(5, 5)
print("Array\n", arr)
print("Absolute difference between the maximum and minimum values in each row\n", absDifference(arr))


Array
 [[ 0.53698377  0.35852017  0.78769593 -0.52460039  0.73996838]
 [ 0.4596811  -0.52858361 -0.24644893  0.77379789  0.4926632 ]
 [ 0.78043035  0.08531258  0.09114224 -0.83972215 -0.30518889]
 [ 0.64446279 -0.46438479 -0.05793421 -0.81822464  0.3242556 ]
 [ 0.30741551 -0.40561994  0.94915985 -0.84750221  0.51141674]]
Absolute difference between the maximum and minimum values in each row
 [1.31229632 1.3023815  1.6201525  1.46268743 1.79666206]


In [51]:
#Please refer the dataframe (farm data) we have created in the training. Please copy that cell and paste it below before starting this part
import random
import pandas as pd

# Define the range for longitude and latitude
lon_range = (-105, -100)
lat_range = (50, 52)

# Define the list of soil types
soil_types = ['black', 'gray', 'dark brown', 'brown', None]

# Create an empty list to store the farms
farms = []

# Generate 40 farms
for i in range(40):
    farm = {
        'farm_name': f'Farm {i+1}', # f is formated string
        'farm_lon': round(random.uniform(lon_range[0], lon_range[1]), 2), # random lon with 2 decimal points
        'farm_lat': round(random.uniform(lat_range[0], lat_range[1]), 2), # rantom lat with 2 decimal points
        'temperature': round(random.uniform(18, 25), 1), #random temp with 1 decimal points
        'precipitation': round(random.uniform(20, 50), 1), # random prec with 1 decimal points
        'soil_type': random.choice(soil_types) # random soil types from above list
    }
    farms.append(farm)
df = pd.DataFrame(farms)
df

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -103.20     50.97         20.5           20.1       black
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown
2     Farm 3   -100.69     50.14         22.7           41.8       brown
3     Farm 4   -103.64     50.42         18.6           34.7        None
4     Farm 5   -104.75     50.01         20.2           32.8  dark brown
5     Farm 6   -103.78     51.60         24.4           43.7       black
6     Farm 7   -103.16     51.62         19.2           33.3        gray
7     Farm 8   -103.64     50.38         20.4           28.7  dark brown
8     Farm 9   -100.55     50.18         23.5           34.8  dark brown
9    Farm 10   -100.16     50.48         19.1           32.8       brown
10   Farm 11   -100.11     51.44         24.4           38.9       brown
11   Farm 12   -103.32     51.21         18.6           37.5        None
12   Farm 13   -102.60     51.28         24.0           33.8  dark brown
13   Farm 14   -102.04     51.62         19.9           21.6       black
14   Farm 15   -102.98     51.53         18.8           40.2  dark brown
15   Farm 16   -102.65     51.63         21.4           49.9        None
16   Farm 17   -101.38     51.73         23.5           34.4       black
17   Farm 18   -103.87     51.01         18.3           49.8       brown
18   Farm 19   -104.65     50.78         24.3           47.9       brown
19   Farm 20   -101.99     51.84         23.0           44.5        None
20   Farm 21   -103.17     51.32         18.4           48.6  dark brown
21   Farm 22   -102.14     51.80         23.0           36.3       black
22   Farm 23   -101.78     50.37         21.6           32.8       brown
23   Farm 24   -104.97     51.42         21.2           22.9  dark brown
24   Farm 25   -100.19     51.07         18.1           27.1       brown
25   Farm 26   -102.39     50.84         20.9           42.5        None
26   Farm 27   -100.59     51.81         22.2           32.8        gray
27   Farm 28   -102.37     50.37         23.1           24.3        None
28   Farm 29   -103.53     51.19         19.2           45.0        gray
29   Farm 30   -101.94     50.90         23.1           21.6        gray
30   Farm 31   -103.87     51.36         19.3           47.6        gray
31   Farm 32   -104.57     51.91         20.5           34.8        gray
32   Farm 33   -102.55     50.21         21.0           25.4       brown
33   Farm 34   -103.03     50.36         20.8           37.6        None
34   Farm 35   -104.99     50.64         20.6           32.0  dark brown
35   Farm 36   -103.55     50.36         23.6           43.8        gray
36   Farm 37   -104.43     50.03         22.4           40.9       brown
37   Farm 38   -102.41     50.81         19.0           27.0       black
38   Farm 39   -101.19     51.07         19.0           48.6        None
39   Farm 40   -101.53     51.01         18.2           29.6        gray

In [52]:
#Temp>20

temp = df[df['temperature'] > 20]
temp


farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -103.20     50.97         20.5           20.1       black
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown
2     Farm 3   -100.69     50.14         22.7           41.8       brown
4     Farm 5   -104.75     50.01         20.2           32.8  dark brown
5     Farm 6   -103.78     51.60         24.4           43.7       black
7     Farm 8   -103.64     50.38         20.4           28.7  dark brown
8     Farm 9   -100.55     50.18         23.5           34.8  dark brown
10   Farm 11   -100.11     51.44         24.4           38.9       brown
12   Farm 13   -102.60     51.28         24.0           33.8  dark brown
15   Farm 16   -102.65     51.63         21.4           49.9        None
16   Farm 17   -101.38     51.73         23.5           34.4       black
18   Farm 19   -104.65     50.78         24.3           47.9       brown
19   Farm 20   -101.99     51.84         23.0           44.5        None
21   Farm 22   -102.14     51.80         23.0           36.3       black
22   Farm 23   -101.78     50.37         21.6           32.8       brown
23   Farm 24   -104.97     51.42         21.2           22.9  dark brown
25   Farm 26   -102.39     50.84         20.9           42.5        None
26   Farm 27   -100.59     51.81         22.2           32.8        gray
27   Farm 28   -102.37     50.37         23.1           24.3        None
29   Farm 30   -101.94     50.90         23.1           21.6        gray
31   Farm 32   -104.57     51.91         20.5           34.8        gray
32   Farm 33   -102.55     50.21         21.0           25.4       brown
33   Farm 34   -103.03     50.36         20.8           37.6        None
34   Farm 35   -104.99     50.64         20.6           32.0  dark brown
35   Farm 36   -103.55     50.36         23.6           43.8        gray
36   Farm 37   -104.43     50.03         22.4           40.9       brown

In [54]:
#Sort the DataFrame by precipitation in descending order.
df.sort_values('precipitation', ascending=False)

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
15   Farm 16   -102.65     51.63         21.4           49.9        None
17   Farm 18   -103.87     51.01         18.3           49.8       brown
38   Farm 39   -101.19     51.07         19.0           48.6        None
20   Farm 21   -103.17     51.32         18.4           48.6  dark brown
18   Farm 19   -104.65     50.78         24.3           47.9       brown
30   Farm 31   -103.87     51.36         19.3           47.6        gray
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown
28   Farm 29   -103.53     51.19         19.2           45.0        gray
19   Farm 20   -101.99     51.84         23.0           44.5        None
35   Farm 36   -103.55     50.36         23.6           43.8        gray
5     Farm 6   -103.78     51.60         24.4           43.7       black
25   Farm 26   -102.39     50.84         20.9           42.5        None
2     Farm 3   -100.69     50.14         22.7           41.8       brown
36   Farm 37   -104.43     50.03         22.4           40.9       brown
14   Farm 15   -102.98     51.53         18.8           40.2  dark brown
10   Farm 11   -100.11     51.44         24.4           38.9       brown
33   Farm 34   -103.03     50.36         20.8           37.6        None
11   Farm 12   -103.32     51.21         18.6           37.5        None
21   Farm 22   -102.14     51.80         23.0           36.3       black
31   Farm 32   -104.57     51.91         20.5           34.8        gray
8     Farm 9   -100.55     50.18         23.5           34.8  dark brown
3     Farm 4   -103.64     50.42         18.6           34.7        None
16   Farm 17   -101.38     51.73         23.5           34.4       black
12   Farm 13   -102.60     51.28         24.0           33.8  dark brown
6     Farm 7   -103.16     51.62         19.2           33.3        gray
22   Farm 23   -101.78     50.37         21.6           32.8       brown
9    Farm 10   -100.16     50.48         19.1           32.8       brown
26   Farm 27   -100.59     51.81         22.2           32.8        gray
4     Farm 5   -104.75     50.01         20.2           32.8  dark brown
34   Farm 35   -104.99     50.64         20.6           32.0  dark brown
39   Farm 40   -101.53     51.01         18.2           29.6        gray
7     Farm 8   -103.64     50.38         20.4           28.7  dark brown
24   Farm 25   -100.19     51.07         18.1           27.1       brown
37   Farm 38   -102.41     50.81         19.0           27.0       black
32   Farm 33   -102.55     50.21         21.0           25.4       brown
27   Farm 28   -102.37     50.37         23.1           24.3        None
23   Farm 24   -104.97     51.42         21.2           22.9  dark brown
29   Farm 30   -101.94     50.90         23.1           21.6        gray
13   Farm 14   -102.04     51.62         19.9           21.6       black
0     Farm 1   -103.20     50.97         20.5           20.1       black

In [58]:
#Filter the DataFrame to include only the farms located within latitude (51.15 & 51.00) range.
df[(df['farm_lat'] >= 51.00) & (df['farm_lat'] <= 51.15)]

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown
17   Farm 18   -103.87     51.01         18.3           49.8       brown
24   Farm 25   -100.19     51.07         18.1           27.1       brown
38   Farm 39   -101.19     51.07         19.0           48.6        None
39   Farm 40   -101.53     51.01         18.2           29.6        gray

In [65]:
#Calculate the standard deviation of precipitation for each soil type.
print(df)
df.groupby('soil_type')['precipitation'].std()

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -103.20     50.97         20.5           20.1       black
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown
2     Farm 3   -100.69     50.14         22.7           41.8       brown
3     Farm 4   -103.64     50.42         18.6           34.7        None
4     Farm 5   -104.75     50.01         20.2           32.8  dark brown
5     Farm 6   -103.78     51.60         24.4           43.7       black
6     Farm 7   -103.16     51.62         19.2           33.3        gray
7     Farm 8   -103.64     50.38         20.4           28.7  dark brown
8     Farm 9   -100.55     50.18         23.5           34.8  dark brown
9    Farm 10   -100.16     50.48         19.1           32.8       brown
10   Farm 11   -100.11     51.44         24.4           38.9       brown
11   Farm 12   -103.32     51.21         18.6           37.5        None
12   Farm 13   -102.60     51.28         24.0      

soil_type
black         9.194654
brown         8.589302
dark brown    8.302259
gray          8.812805
Name: precipitation, dtype: float64

In [72]:
#Calculate the cumulative sum of precipitation for each soil type.
print(df)
df['precipitation'].cumsum()

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -103.20     50.97         20.5           20.1       black
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown
2     Farm 3   -100.69     50.14         22.7           41.8       brown
3     Farm 4   -103.64     50.42         18.6           34.7        None
4     Farm 5   -104.75     50.01         20.2           32.8  dark brown
5     Farm 6   -103.78     51.60         24.4           43.7       black
6     Farm 7   -103.16     51.62         19.2           33.3        gray
7     Farm 8   -103.64     50.38         20.4           28.7  dark brown
8     Farm 9   -100.55     50.18         23.5           34.8  dark brown
9    Farm 10   -100.16     50.48         19.1           32.8       brown
10   Farm 11   -100.11     51.44         24.4           38.9       brown
11   Farm 12   -103.32     51.21         18.6           37.5        None
12   Farm 13   -102.60     51.28         24.0      

0       20.1
1       67.0
2      108.8
3      143.5
4      176.3
5      220.0
6      253.3
7      282.0
8      316.8
9      349.6
10     388.5
11     426.0
12     459.8
13     481.4
14     521.6
15     571.5
16     605.9
17     655.7
18     703.6
19     748.1
20     796.7
21     833.0
22     865.8
23     888.7
24     915.8
25     958.3
26     991.1
27    1015.4
28    1060.4
29    1082.0
30    1129.6
31    1164.4
32    1189.8
33    1227.4
34    1259.4
35    1303.2
36    1344.1
37    1371.1
38    1419.7
39    1449.3
Name: precipitation, dtype: float64

In [81]:
#Determine the top 3 farms with the highest average temperature.
top_3_temp = df['temperature'].nlargest(3)
#data[data['Column_Name'].isin(top_3_largest_values)]['Another_Column']

df[df['temperature'].isin(top_3_temp)][['farm_name', 'temperature']]

farm_name  temperature
5     Farm 6         24.4
10   Farm 11         24.4
18   Farm 19         24.3

In [96]:
#Find famrs in each soil type that have the highest temperature.
df.groupby('soil_type')['temperature','farm_name'].max()

/var/folders/zj/tr5b1jpx1v3gc2xszyxdc4jc0000gn/T/ipykernel_36301/2172935269.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby('soil_type')['temperature','farm_name'].max()


temperature farm_name
soil_type                        
black              24.4    Farm 6
brown              24.4   Farm 37
dark brown         24.0    Farm 9
gray               23.6    Farm 7

In [95]:
#Create new column 'percentage_tot_prec' and add the percentage contribution of each farm's precipitation (relative to total precipitation) to the column.

soil_type
black         24.4
brown         24.4
dark brown    24.0
gray          23.6
Name: temperature, dtype: float64

In [99]:
total_prec = df['precipitation'].sum()
print(total_prec)

df['percentage_tot_prec'] = (df['precipitation'] / total_prec) * 100
df

1449.3


farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -103.20     50.97         20.5           20.1       black   
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown   
2     Farm 3   -100.69     50.14         22.7           41.8       brown   
3     Farm 4   -103.64     50.42         18.6           34.7        None   
4     Farm 5   -104.75     50.01         20.2           32.8  dark brown   
5     Farm 6   -103.78     51.60         24.4           43.7       black   
6     Farm 7   -103.16     51.62         19.2           33.3        gray   
7     Farm 8   -103.64     50.38         20.4           28.7  dark brown   
8     Farm 9   -100.55     50.18         23.5           34.8  dark brown   
9    Farm 10   -100.16     50.48         19.1           32.8       brown   
10   Farm 11   -100.11     51.44         24.4           38.9       brown   
11   Farm 12   -103.32     51.21         18.6           37.5        None   
12   Farm 13   -102.60     51.28         24.0           33.8  dark brown   
13   Farm 14   -102.04     51.62         19.9           21.6       black   
14   Farm 15   -102.98     51.53         18.8           40.2  dark brown   
15   Farm 16   -102.65     51.63         21.4           49.9        None   
16   Farm 17   -101.38     51.73         23.5           34.4       black   
17   Farm 18   -103.87     51.01         18.3           49.8       brown   
18   Farm 19   -104.65     50.78         24.3           47.9       brown   
19   Farm 20   -101.99     51.84         23.0           44.5        None   
20   Farm 21   -103.17     51.32         18.4           48.6  dark brown   
21   Farm 22   -102.14     51.80         23.0           36.3       black   
22   Farm 23   -101.78     50.37         21.6           32.8       brown   
23   Farm 24   -104.97     51.42         21.2           22.9  dark brown   
24   Farm 25   -100.19     51.07         18.1           27.1       brown   
25   Farm 26   -102.39     50.84         20.9           42.5        None   
26   Farm 27   -100.59     51.81         22.2           32.8        gray   
27   Farm 28   -102.37     50.37         23.1           24.3        None   
28   Farm 29   -103.53     51.19         19.2           45.0        gray   
29   Farm 30   -101.94     50.90         23.1           21.6        gray   
30   Farm 31   -103.87     51.36         19.3           47.6        gray   
31   Farm 32   -104.57     51.91         20.5           34.8        gray   
32   Farm 33   -102.55     50.21         21.0           25.4       brown   
33   Farm 34   -103.03     50.36         20.8           37.6        None   
34   Farm 35   -104.99     50.64         20.6           32.0  dark brown   
35   Farm 36   -103.55     50.36         23.6           43.8        gray   
36   Farm 37   -104.43     50.03         22.4           40.9       brown   
37   Farm 38   -102.41     50.81         19.0           27.0       black   
38   Farm 39   -101.19     51.07         19.0           48.6        None   
39   Farm 40   -101.53     51.01         18.2           29.6        gray   

    percentage_tot_prec  
0              1.386876  
1              3.236045  
2              2.884151  
3              2.394259  
4              2.263162  
5              3.015249  
6              2.297661  
7              1.980266  
8              2.401159  
9              2.263162  
10             2.684054  
11             2.587456  
12             2.332160  
13             1.490375  
14             2.773753  
15             3.443041  
16             2.373560  
17             3.436142  
18             3.305044  
19             3.070448  
20             3.353343  
21             2.504657  
22             2.263162  
23             1.580073  
24             1.869868  
25             2.932450  
26             2.263162  
27             1.676671  
28             3.104947  
29             1.490375  
30             3.284344  
31             2.401159  
32             1.752570  
33

In [100]:
#Create a new column called "precipitation_rank" that ranks the farms based on their precipitation in ascending order, with ties being assigned the same rank.
df['precipitation_rank'] = df['precipitation'].rank(method='min')
df

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -103.20     50.97         20.5           20.1       black   
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown   
2     Farm 3   -100.69     50.14         22.7           41.8       brown   
3     Farm 4   -103.64     50.42         18.6           34.7        None   
4     Farm 5   -104.75     50.01         20.2           32.8  dark brown   
5     Farm 6   -103.78     51.60         24.4           43.7       black   
6     Farm 7   -103.16     51.62         19.2           33.3        gray   
7     Farm 8   -103.64     50.38         20.4           28.7  dark brown   
8     Farm 9   -100.55     50.18         23.5           34.8  dark brown   
9    Farm 10   -100.16     50.48         19.1           32.8       brown   
10   Farm 11   -100.11     51.44         24.4           38.9       brown   
11   Farm 12   -103.32     51.21         18.6           37.5        None   
12   Farm 13   -102.60     51.28         24.0           33.8  dark brown   
13   Farm 14   -102.04     51.62         19.9           21.6       black   
14   Farm 15   -102.98     51.53         18.8           40.2  dark brown   
15   Farm 16   -102.65     51.63         21.4           49.9        None   
16   Farm 17   -101.38     51.73         23.5           34.4       black   
17   Farm 18   -103.87     51.01         18.3           49.8       brown   
18   Farm 19   -104.65     50.78         24.3           47.9       brown   
19   Farm 20   -101.99     51.84         23.0           44.5        None   
20   Farm 21   -103.17     51.32         18.4           48.6  dark brown   
21   Farm 22   -102.14     51.80         23.0           36.3       black   
22   Farm 23   -101.78     50.37         21.6           32.8       brown   
23   Farm 24   -104.97     51.42         21.2           22.9  dark brown   
24   Farm 25   -100.19     51.07         18.1           27.1       brown   
25   Farm 26   -102.39     50.84         20.9           42.5        None   
26   Farm 27   -100.59     51.81         22.2           32.8        gray   
27   Farm 28   -102.37     50.37         23.1           24.3        None   
28   Farm 29   -103.53     51.19         19.2           45.0        gray   
29   Farm 30   -101.94     50.90         23.1           21.6        gray   
30   Farm 31   -103.87     51.36         19.3           47.6        gray   
31   Farm 32   -104.57     51.91         20.5           34.8        gray   
32   Farm 33   -102.55     50.21         21.0           25.4       brown   
33   Farm 34   -103.03     50.36         20.8           37.6        None   
34   Farm 35   -104.99     50.64         20.6           32.0  dark brown   
35   Farm 36   -103.55     50.36         23.6           43.8        gray   
36   Farm 37   -104.43     50.03         22.4           40.9       brown   
37   Farm 38   -102.41     50.81         19.0           27.0       black   
38   Farm 39   -101.19     51.07         19.0           48.6        None   
39   Farm 40   -101.53     51.01         18.2           29.6        gray   

    percentage_tot_prec  precipitation_rank  
0              1.386876                 1.0  
1              3.236045                34.0  
2              2.884151                28.0  
3              2.394259                19.0  
4              2.263162                12.0  
5              3.015249                30.0  
6              2.297661                16.0  
7              1.980266                 9.0  
8              2.401159                20.0  
9              2.263162                12.0  
10             2.684054                25.0  
11             2.587456                23.0  
12             2.332160                17.0  
13             1.490375                 2.0  
14             2.773753                26.0  
15             3.443041                40.0  
16             2.373560                18.0  
17             3.436142                39.0  
18          

In [106]:
#Normalize the temperature column to a range between 0 and 1 for each farm.
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

# Normalize the temperature column
df['normalized_temperature_scaler'] = scaler.fit_transform(df[['temperature']])
df
#df_z_scaled[column] = (df_z_scaled[column] - df_z_scaled[column].mean()) / df_z_scaled[column].std()    
df['normalized_temperature_zscore'] = (df['temperature'] - df['temperature'].mean()) / df['temperature'].std()
df

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -103.20     50.97         20.5           20.1       black   
1     Farm 2   -101.72     51.14         20.5           46.9  dark brown   
2     Farm 3   -100.69     50.14         22.7           41.8       brown   
3     Farm 4   -103.64     50.42         18.6           34.7        None   
4     Farm 5   -104.75     50.01         20.2           32.8  dark brown   
5     Farm 6   -103.78     51.60         24.4           43.7       black   
6     Farm 7   -103.16     51.62         19.2           33.3        gray   
7     Farm 8   -103.64     50.38         20.4           28.7  dark brown   
8     Farm 9   -100.55     50.18         23.5           34.8  dark brown   
9    Farm 10   -100.16     50.48         19.1           32.8       brown   
10   Farm 11   -100.11     51.44         24.4           38.9       brown   
11   Farm 12   -103.32     51.21         18.6           37.5        None   
12   Farm 13   -102.60     51.28         24.0           33.8  dark brown   
13   Farm 14   -102.04     51.62         19.9           21.6       black   
14   Farm 15   -102.98     51.53         18.8           40.2  dark brown   
15   Farm 16   -102.65     51.63         21.4           49.9        None   
16   Farm 17   -101.38     51.73         23.5           34.4       black   
17   Farm 18   -103.87     51.01         18.3           49.8       brown   
18   Farm 19   -104.65     50.78         24.3           47.9       brown   
19   Farm 20   -101.99     51.84         23.0           44.5        None   
20   Farm 21   -103.17     51.32         18.4           48.6  dark brown   
21   Farm 22   -102.14     51.80         23.0           36.3       black   
22   Farm 23   -101.78     50.37         21.6           32.8       brown   
23   Farm 24   -104.97     51.42         21.2           22.9  dark brown   
24   Farm 25   -100.19     51.07         18.1           27.1       brown   
25   Farm 26   -102.39     50.84         20.9           42.5        None   
26   Farm 27   -100.59     51.81         22.2           32.8        gray   
27   Farm 28   -102.37     50.37         23.1           24.3        None   
28   Farm 29   -103.53     51.19         19.2           45.0        gray   
29   Farm 30   -101.94     50.90         23.1           21.6        gray   
30   Farm 31   -103.87     51.36         19.3           47.6        gray   
31   Farm 32   -104.57     51.91         20.5           34.8        gray   
32   Farm 33   -102.55     50.21         21.0           25.4       brown   
33   Farm 34   -103.03     50.36         20.8           37.6        None   
34   Farm 35   -104.99     50.64         20.6           32.0  dark brown   
35   Farm 36   -103.55     50.36         23.6           43.8        gray   
36   Farm 37   -104.43     50.03         22.4           40.9       brown   
37   Farm 38   -102.41     50.81         19.0           27.0       black   
38   Farm 39   -101.19     51.07         19.0           48.6        None   
39   Farm 40   -101.53     51.01         18.2           29.6        gray   

    percentage_tot_prec  precipitation_rank  normalized_temperature  \
0              1.386876                 1.0                0.380952   
1              3.236045                34.0                0.380952   
2              2.884151                28.0                0.730159   
3              2.394259                19.0                0.079365   
4              2.263162                12.0                0.333333   
5              3.015249                30.0                1.000000   
6              2.297661                16.0                0.174603   
7              1.980266                 9.0                0.365079   
8              2.401159                20.0                0.857143   
9              2.263162                12.0                0.158730   
10             2.684054                25.0                1.000000   
11             2.587456           